### ISSUE TITLE
crashing on initialization

### ISSUE THREAD

**Issue by AntidotAleks** [dima-dencep/online-emotes#5]
### Minecraft version.

1.19.2

### Emotecraft version.

2.2.5

### Online Emotes version.

1.0.2

### What happened?

game crashed on initialization

### Relevant logs

Exception in thread "Thread-3" java.lang.IllegalStateException: Emotecraft proxy is NOT loaded. You can only register instances before loading.
at TRANSFORMER/emotecraft@2.2.5/io.github.kosmx.emotes.api.proxy.EmotesProxyManager.getManager(EmotesProxyManager.java:83)
at TRANSFORMER/emotecraft@2.2.5/io.github.kosmx.emotes.api.proxy.EmotesProxyManager.disconnectInstance(EmotesProxyManager.java:72)
at TRANSFORMER/emotecraft@2.2.5/io.github.kosmx.emotes.api.proxy.AbstractNetworkInstance.disconnect(AbstractNetworkInstance.java:111)
at TRANSFORMER/online_emotes@1.19.4-1.0.2-forge/com.github.dima_dencep.mods.online_emotes.network.OnlineProxyImpl.disconnect(OnlineProxyImpl.java:132)
at TRANSFORMER/online_emotes@1.19.4-1.0.2-forge/com.github.dima_dencep.mods.online_emotes.OnlineEmotes.lambda$onInitializeClient$0(OnlineEmotes.java:28)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by dima-dencep** [comment]
Try updating emotecraft and the required libraries to the latest version

https://modrinth.com/mod/emotecraft/version/2.2.7-b.build.48+1.19.2-forge
https://modrinth.com/mod/playeranimator/version/1.0.2-forge
https://modrinth.com/mod/bendy-lib/version/2.1.1-forge
